### ISSUE TITLE
Create the Project

### ISSUE THREAD

**Issue by jramiresbrito** [jramiresbrito/onion-api#1]
## Intro
Following the requirements of the test, it will be necessary to put the code responsible for interacting with Starlink API under a Web Server.

## Tasks
- [x] Create a Rails API project
- [x] Update gitignore
- [x] Config rubocop and solargraph for coding styling
- [x] Configure the CORS policy
   - [x] add cors.rb initializer
- [x] Initial version of README.md
- [x] Dockerize it to make the setup easier
   - [x] Add .dockerignore
   - [x] Add Dockerfile
   - [x] Add a entrypoint.sh to install dependencies
   - [x] Add docker-compose.yml
       - [x] Add the Rails container
       - [ ] Will I need a Yard container for documentation?
       - [ ] It doesn't seem to be necessary for a DB container, anyways add a container for DB if needed
    - [x]  Add a script to make easier to run all the needed containers.
 - [x] Add a test endpoint and controller to check if everything is working
   - [x] HomeController with a get route to index action. It should return a simple json { ok: true }
 - [x] Configure the test framework
     - [x] Test the HomeController
