### ISSUE TITLE
Add an endpoint responsible for find the closest satelites using SpacexAPI

### ISSUE THREAD

**Issue by jramiresbrito** [jramiresbrito/onion-api#2]
## Intro

As discussed in the test it is necessary to add an endpoint for handling the data available in https://api.spacexdata.com/v4/starlink. This endpoint should receive three arguments:

- latitude (number)
- longitude (number)
- Amount (number) The N-first closest satellites of the given coordinates.

Request Example:
```json
{
   "lat": -19.8896944,
   "lon": -43.9246297,
   "amount": 2	
}
```

## Tasks
- [ ] Add StarlinkController
   - [ ] Add nearby action
      - [ ] It should receive **:lat**, **:lon** and **:amount** through starlink_params (use strong params here)
      - [ ] As we don't have any model, add an validation method for check the input format:
         - [ ] add validate_input method for check the rules
             - [ ] lat must be a float between -90 and 90
             - [ ] lon must be a float between -180 and 180
             - [ ] amount must be a positive integer
     - [ ]  As there isn't any requirement to permit complex queries, add a method to always query the API following:
        - [ ] select the fields:
            - [ ] id
            - [ ] latitude
            - [ ] longitude
            - [ ] OBJECT_NAME (the satellite name wich is under the spaceTrack key)
        - [ ] latitude and longitude must have values (many records are null)
      - [ ] Use the [Haversine gem](https://github.com/kristianmandrup/haversine) to compute the distance (in miles) between the user coordinates and each satellite.
      - [ ] Return an array having the size according with the user request (**:amount** ) having the following data of the closests satellites of the given coordinates:
      
```javascript
{
   id: (satellite id)
   name: (satellite name)
   sat_lat:  (satellite latitude)
   sat_lon: (satellite longitude)
   input_lat: (the lattitude provided by the user)
   input_lon: (the longitude provided by the user)
   distance: (the calculated distance using the Haversine gem)
}
```

**Comment by jramiresbrito** [comment]
Fun Fact:

3 years ago I've done the Haversine calculations by hand in order to discover some data related air trips:

https://replit.com/@jramiresbrito/Haversine-Distance#main.py :)

PS: I've learned Python in 1 day to do this script (and a Django app), so, please don't push so hard on it haha
